### ISSUE TITLE
Channel error

### ISSUE THREAD

**Issue by aamber2231** [Foreheadchann/ViaMCP-Reborn#6] opened 2021-07-14 17:14 UTC
hi when i change my protocol version from 1.8 to any other one and i try to connect to a server or ping one i get this error
Jul 14, 2021 1:13:12 PM io.netty.channel.ChannelInitializer channelRegistered
WARNING: Failed to initialize a channel. Closing: [id: 0xe6cf1c65]
pls help

**Comment by aamber2231** [comment] 2021-07-14 17:16
Jul 14, 2021 1:16:18 PM io.netty.channel.ChannelInitializer channelRegistered
WARNING: Failed to initialize a channel. Closing: [id: 0xfaaf02e5]
java.util.NoSuchElementException: encoder
	at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:907)
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:157)
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:150)
	at net.minecraft.network.NetworkManager$5.initChannel(NetworkManager.java:402)
	at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:69)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRegistered(DefaultChannelPipeline.java:732)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:442)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$100(AbstractChannel.java:374)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:418)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Foreheadchann** [comment] 2021-07-14 17:16
Are you sure you followed the README file on the main page fully? As that error usually means something wasnt loaded.

**Comment by aamber2231** [comment] 2021-07-14 17:17
im pretty sure i followed it

**Comment by aamber2231** [comment] 2021-07-14 17:17
everything loaded correctly but when i try changing versions it just dies

**Comment by Foreheadchann** [comment] 2021-07-14 17:24
Try following this (it is spoken in french and is for 1.12.2, but just do it in 1.8.x with the 1.8.x src) and it might help (not my video): https://youtu.be/EuqPTI3xIk0

**Comment by aamber2231** [comment] 2021-07-14 17:31
OMG IT WORKS! YOUR A LIFE SAVER! THX FOR THE QUICK RESPONSE <3

**Comment by Foreheadchann** [comment] 2021-07-14 17:32
Not a problem, what was the issue though?

**Comment by aamber2231** [comment] 2021-07-14 17:34
Turns out i was a retard and put the code in the wrong place

**Comment by Foreheadchann** [comment] 2021-07-14 17:36
Yeah minecraft network code sometimes confusing, will be closing this now, as the issue is resolved.
Have a good day! :)

**Closed by Foreheadchann** 2021-07-14 17:36 UTC
